shell="/bin/bash"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
  background= "0x000b1e"
  foreground= "0x0abdc6"
  
[colors.normal]
    black=   "0x123e7c"
    red=     "0xff0000"
    green=   "0xd300c4"
    yellow=  "0xf57800"
    blue=    "0x123e7c"
    magenta= "0x711c91"
    cyan=    "0x0abdc6"
    white=   "0xd7d7d5"

[colors.bright]
    black=   "0x1c61c2"
    red=     "0xff0000"
    green=   "0xd300c4"
    yellow=  "0xf57800"
    blue=    "0x00ff00"
    magenta= "0x711c91"
    cyan=    "0x0abdc6"
    white=   "0xd7d7d5"

[cursor]
style = "Beam"

[colors.cursor]
 text=   "0x000b1e"
 cursor= "0x0abdc6"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000
multiplier = 3 

[window]
dynamic_padding = false
opacity = 0.7
title = "Alacritty"
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
